[package]
name = "echo-multipart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
echo-body = { path = "../echo-body", version = "0.1.0" }
http = "0.2"
multer = "2"
futures-util = "0.3"
